language: node_js
node_js:
- stable

env:
  global:
    - secure: {{API_KEY}}

deploy:
  provider: heroku
  app: rentserviceweb
  api_key:
    secure: #{process.env.API_KEY}
  run:
    - npm run migrate